### ISSUE TITLE
Anime/Manga status

### ISSUE THREAD

**Issue by rushsteve1** [zeyla/kitsu.rs#9]
Anime and Manga have a `status` field in the Kitsu API, so why does this library use a function to calculate the `airing` and `finished` status? Neither of those is a term used by the API either.
I would switch it all over myself but I get the feeling this was done deliberately and I don't want to break other people's stuff that depends on these.

**Comment by rushsteve1** [comment]
So I completed the addition of the `status` field to the `AnimeAttributes` and `MangaAttributes` structs. It can be found here: https://github.com/rushsteve1/kitsu.rs/commit/35ebcb115c03b5f87c70e070fd2332384606d6e8

For now I left the existing code, but I don't see a reason to have both other than backwards compatibility.

**Comment by rushsteve1** [comment]
@zeyla hate to ping you but can I get a response please?

**Comment by Flat** [comment]
IIrc this was due to kitsu not always having the best data when it comes to airing. It wouldn't return the correct status after a series had ended, or just plain didn't have it, therefore if it had an end date it was finished. I could be wrong though.

**Comment by zeyla** [comment]
Sorry for the late reply. I believe Flat is correct, but I'd have to do some testing on it this weekend.

**Comment by zeyla** [comment]
Flat was correct. I have cherry-picked your commit into `master` and added additional documentation to `{Anime,Manga}Attributes::airing_status`.
